In [1]:
import cv2

In [2]:
img=cv2.imread('geeks14.png',1)
img1=cv2.imread('geeks14.png',0)


In [3]:
print(img)

[[[ 87 157  14]
  [ 87 157  14]
  [ 87 157  14]
  ...
  [ 87 157  14]
  [ 87 157  14]
  [ 87 157  14]]

 [[ 87 157  14]
  [ 87 157  14]
  [ 87 157  14]
  ...
  [ 87 157  14]
  [ 87 157  14]
  [ 87 157  14]]

 [[ 87 157  14]
  [ 87 157  14]
  [ 87 157  14]
  ...
  [ 87 157  14]
  [ 87 157  14]
  [ 87 157  14]]

 ...

 [[ 72 133   9]
  [ 72 133   9]
  [ 72 133   9]
  ...
  [ 87 157  14]
  [ 87 157  14]
  [ 87 157  14]]

 [[ 72 133   9]
  [ 72 133   9]
  [ 72 133   9]
  ...
  [ 87 157  14]
  [ 87 157  14]
  [ 87 157  14]]

 [[ 72 133   9]
  [ 72 133   9]
  [ 72 133   9]
  ...
  [ 87 157  14]
  [ 87 157  14]
  [ 87 157  14]]]


In [4]:
print(img1)

[[106 106 106 ... 106 106 106]
 [106 106 106 ... 106 106 106]
 [106 106 106 ... 106 106 106]
 ...
 [ 88  88  88 ... 106 106 106]
 [ 88  88  88 ... 106 106 106]
 [ 88  88  88 ... 106 106 106]]


In [5]:
print(type(img1))

<class 'numpy.ndarray'>


In [6]:
print(img1.shape)

(225, 225)


# Display the image

In [7]:
img=cv2.imread('geeks14.png',0)
cv2.imshow("Title",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Resizing an image

In [8]:
import cv2
#Black and white
img=cv2.imread('geeks14.png',0)

resize_image=cv2.resize(img,(100,1000))

cv2.imshow("Title",resize_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Resize

In [9]:
resize=cv2.resize(img,(int(img.shape[1]/2),int(img.shape[0]/2)))

# Face detection

In [10]:
import cv2


face_cascade=cv2.CascadeClassifier(r'haarcascade_frontalface_default.xml')


img=cv2.imread('photo.jpg',cv2.COLOR_BGR2GRAY)

gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

faces=face_cascade.detectMultiScale(gray_img,scaleFactor=1.05,minNeighbors=5)


print(type(faces))
print(faces)


<class 'numpy.ndarray'>
[[412 302 754 754]
 [544 963 440 440]]


In [11]:
for x,y,w,h in faces:
    img=cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)
    
resized=cv2.resize(img,(int(img.shape[1]/7),int(img.shape[1]/7)))
cv2.imshow("Gray",resized)
cv2.waitKey(0)
cv2.destroyAllWindows()    
    
    
    
    

# Capture Video

In [12]:
import cv2,time

video=cv2.VideoCapture(0)
check,frame=video.read()

time.sleep(15)
video.release()
print(check)
print(frame)

True
[[[ 88   1  58]
  [  0   0   0]
  [  0   0 112]
  ...
  [  0 208 186]
  [ 35   8   0]
  [  0   0   0]]

 [[208 186  35]
  [  8   0   0]
  [  0   0 208]
  ...
  [  0 208 186]
  [ 35   8   0]
  [  0   0   0]]

 [[208 186  35]
  [  8   0   0]
  [  0   0 208]
  ...
  [  0 208 186]
  [ 35   8   0]
  [  0   0   0]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]


In [13]:
cv2.imshow("Gray",frame)
cv2.waitKey(0)
cv2.destroyAllWindows()    


# Capturing Video

In [14]:
import cv2,time

video=cv2.VideoCapture(0)
a=1

while True:
    a=a+1
    check,frame=video.read()
    print(frame)
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow("capture",gray)
    key=cv2.waieKey(1)
    if key == ord('q'):
        breack
    
print(a)    
video.release()
cv2.destroyallWindows()



[[[70 74 73]
  [68 72 71]
  [70 76 70]
  ...
  [73 78 74]
  [65 73 68]
  [40 48 43]]

 [[75 79 78]
  [71 75 74]
  [65 74 72]
  ...
  [65 72 70]
  [60 68 63]
  [52 60 55]]

 [[70 81 79]
  [64 75 73]
  [66 75 73]
  ...
  [58 65 63]
  [56 63 61]
  [56 63 61]]

 ...

 [[ 3 18 38]
  [ 0 15 35]
  [ 6 18 29]
  ...
  [ 0  0  8]
  [ 0  0  7]
  [ 0  0  5]]

 [[ 7 19 37]
  [ 6 18 36]
  [ 3 15 26]
  ...
  [ 0  0  6]
  [ 0  0  4]
  [ 0  0  5]]

 [[19 17 35]
  [18 16 34]
  [12 12 25]
  ...
  [ 0  0  3]
  [ 0  0  3]
  [ 0  0  4]]]


AttributeError: module 'cv2.cv2' has no attribute 'waieKey'